### ISSUE TITLE
About the image file name.

### ISSUE THREAD

**Issue by loopCM** [web-vision/magento-high-speed-import#1]
Hello, I have a problem. I have a large number of pictures. The pictures are placed under the folder named SKU, and the pictures in the folder are named as digital 1.jpg, 2.jpg, 3.jpg, 4.jpg..... 9. JPG, I think it is helpful for us to upload the product quickly, but when I use MHSI, these don't work, because if we need to name the image according to the rules of MHSI, we need to spend a lot of energy, is there a better way?

**Comment by borishinzer** [comment]
Hi,
have you tried to name the pictures with the SKU? Then MHSI would find them, without giving the image name in the import file. Like mentioned here: https://support.web-vision.de/en/magento-high-speed-import-3-1-english-documentation/magento-high-speed-import-mhsi-english/magento-high-speed-import-import-products-with-images

**Comment by loopCM** [comment]
I have tried, but we have a lot of images, so we have 1. JPG under each folder... 9.jpg like this
